# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Warlock Front End
email: sproctor@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Warlock is an open source front end for Simutronics games.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://warlockfe.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username:
github_username:  WarlockFE

show_excerpts: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - title: Docs
    url: http://github.com/WarlockFe/warlock2/wiki
  - title: Releases
    url: https://github.com/WarlockFE/warlock2/releases
  - contact.md
  - screenshots.md

authors:
  sproctor:
    name: Sean Proctor
    email: sproctor@gmail.com
    web: http://www.seanproctor.com/
    github: sproctor
  marshall:
    name: Marshall
    email: marshal__NOSPAM__@arcaner.com
    web: http://www.arcaner.com/
    github: marshall
  kassah:
    name: William Lightning
    email: kassah@gmail.com
    github: kassah

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
